### ISSUE TITLE
Healing Elixir spell is missing

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#1]
Healing Elixir

1st-level conjuration

Casting Time: 1 minute
Range: Self
Components: V, S, M (alchemist’s supplies)
Duration: 24 hours

You create a healing elixir in a simple vial that appears in your hand. The elixir retains its potency for the duration or until it’s consumed, at which point the vial vanishes.

As an action, a creature can drink the elixir or administer it to another creature. The drinker regains 2d4 + 2 hit points.

Spell Lists. Warlock, Wizard

**Comment by prophet-kn** [comment]
Hi,

I have noticed I was missing about 5 others spells from Unearthened Arcana books, including Healing Elixir, they have since been pushed in.

Thanks for raising the issue!
