### ISSUE TITLE
PCF-5: Spells falling off edges on android

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#41]
**Describe the bug**
On an android (fairphone 2), the spell list slightly falls off the sides of the screen at both edges

**To Reproduce**
1. Go to 'List of Spells'
2. See that the spells fall off the sides of the screen at both edges

**Expected behavior**
The spells to be fully shown.

**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - OS: Android 7.1.2
 - Browser Chrome
 - Version 80.0.3987.99

![image](https://user-images.githubusercontent.com/17615620/74778825-09758680-52a5-11ea-911c-050665977807.png)

**Comment by prophet-kn** [comment]
Hm, good catch, doesn't happen on mine. Could add some padding (like 10-15px) to main container for all the views. Or does it happen just on spells?

**Comment by CuriousCactus** [comment]
Had a go at fixing this and some other issues on firefox I found related to width:
https://github.com/prophet-kn/dnd_spells_book/pull/46
(side-note: should this be linking my PRs automatically? Am I naming something wrongly?)

**Comment by prophet-kn** [comment]
Dunno about the side note, github was still in progress of integrating these connections, so maybe it works now? dunno, either way, this was done by you :)
