### ISSUE TITLE
PC-20: Spell cards should show which classes can cast the spell

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#44]
**Is your feature request related to a problem? Please describe.**
When I'm looking through spells that could solve a specific problem, I want to know which classes can cast them. I end up googling the spell to find this out, leaving the app.

**Describe the solution you'd like**
A line in the card that shows the classes that can cast the spell.

**Comment by prophet-kn** [comment]
There is data for it already in the json, where could this be added, got any ideas? maybe below a horizontal line at the bottom of the spell when it's expanded? like 'Castable by: bla, bla, bla' in italics

**Comment by CuriousCactus** [comment]
PR already made, but I can change to this styling if you want?
https://github.com/prophet-kn/dnd_spells_book/pull/45/files

**Comment by prophet-kn** [comment]
Am just afraid of clogging it too much in that spot, esp. for users that have selected their class, now it also shows this out right, so just a thought :)

**Comment by CuriousCactus** [comment]
Done!
