### ISSUE TITLE
PC-21: Better search - tags

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#47]
**Is your feature request related to a problem? Please describe.**
I would like a better way to find categories of spells, e.g. a spell to transport an object. At the moment I have to guess what words might be in the name of a spell I want.

**Describe the solution you'd like**
I would like the spells to be tagged, so that I can choose to view spells with the 'transportation' tag, for example.
The tags could be selected from a dropdown (which could allow multiple selections), or a text box with autocomplete, with the currently selected tags listed below, with crosses so they can be deselected.

**Comment by prophet-kn** [comment]
Makes sense, this would have to be a new component that extends all current spells also. Also should be decided on per-spell basis. Aside of 'transportation', what other tags do you have in mind?

**Comment by CuriousCactus** [comment]
I was thinking this feature would bring in the Damage/Support/Utility tags to start with.

Some tags could be:

damage
transport
healing
summoning
protection
skills

Possibly in a different key in the json (?):

melee
ranged
aoe

I'd have to have a proper think when I start categorising, but something like this.

**Comment by prophet-kn** [comment]
Ok, so sort of expanding upon the type such as damage/support/utility. Yeah, as a new component it'd work nicely. :)
