### ISSUE TITLE
PC-22: Icons for tags

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#52]
**Is your feature request related to a problem? Please describe.**
I would like to be able to quickly see what category a spell is in without expanding and reading the spell

**Describe the solution you'd like**
I would like icons to show next to the spell name, designating what category/categories it is in

**Comment by prophet-kn** [comment]
Sounds good, but we have to be careful not to overpopulate the bar, especially on mobile, and we already have a chevron, a pin, a title and for some a damage type icon :)

**Comment by prophet-kn** [comment]
and a level requirement part :P
