### ISSUE TITLE
PC-24: Rearrange menu

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#55]
**Is your feature request related to a problem? Please describe.**

I keep clicking on the burger menu icon instead of the filters button. This is partially because the cross to close the filters menu is in the same screen position as the burger menu.

**Describe the solution you'd like**

The menu layout should be:

[burger menu][search box][filter button]

The button with the word "Filters" could be replaced with a funnel SVG.

**Comment by prophet-kn** [comment]
I actually keep clicking/tapping that too. :)

But no, I don't think we should re-arrange the items, I think we need a proper navigation, possibly even sticky, and no lengthier than 50px height etc. One that could be global on all the pages.

**Comment by prophet-kn** [comment]
Actually should think about introducing react-router or something, to make proper paths and nav/etc

**Comment by CuriousCactus** [comment]
![Screenshot from 2020-07-19 11-43-27](https://user-images.githubusercontent.com/17615620/87870926-2ed20200-c9b5-11ea-87dd-9c65e8978eee.png)
Ugly AF but getting there!

**Comment by prophet-kn** [comment]
merged, thanks!
