### ISSUE TITLE
PC-25: Implement linting

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#56]
**Is your feature request related to a problem? Please describe.**
The code should be clearly and consistently laid out according to coding standards

**Describe the solution you'd like**
Implement linting of js and scss.
There should be linting config files which can be found by your code editor so mistakes can be highlighted as you're editing.
The terminal running the local server could also prompt you about code formatting problems, as it already prompts about unused variables etc.

**Comment by prophet-kn** [comment]
merged, thanks!
