### ISSUE TITLE
PCF-9: Errata to Xanathar's Guide to Everything are not included

### ISSUE THREAD

**Issue by CuriousCactus** [prophet-kn/dnd_spells_book#70]
**Describe the bug**
[These](https://media.wizards.com/2020/dnd/downloads/XGtE-Errata.pdf) errata to Xanathar's Guide to Everything are not included.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to spells list
2. Click on Healing Spirit (or others listed in the errata)
3. See that the erratum is not included (and that this spell is massively OP out of combat)

**Expected behaviour**
The errata in the document above should be included.

**Comment by prophet-kn** [comment]
was merged (:
